# Generated by Django 6.0.3 on 2026-04-02 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtkenMadde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, unique=True)),
                ('cas_no', models.CharField(blank=True, max_length=50, verbose_name='CAS Numarası')),
                ('aktif', models.BooleanField(default=True)),
                ('onaylandi', models.BooleanField(default=False)),
                ('giris', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etken Madde',
                'verbose_name_plural': 'Etken Maddeler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Gubre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticari_ad', models.CharField(max_length=200)),
                ('tur', models.CharField(choices=[('makro', 'Makro Gübre'), ('mikro', 'Mikro Gübre'), ('organik', 'Organik Gübre'), ('yaprak', 'Yaprak Gübresi'), ('toprak', 'Toprak Düzenleyici'), ('diger', 'Diğer')], max_length=20)),
                ('formulasyon', models.CharField(max_length=50)),
                ('doz_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('doz_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('doz_birimi', models.CharField(max_length=50)),
                ('uygulama_yontemi', models.CharField(max_length=100)),
                ('bekleme_suresi', models.PositiveIntegerField(blank=True, null=True)),
                ('kullanim_tavsiyesi', models.TextField(blank=True)),
                ('notlar', models.TextField(blank=True)),
                ('ambalaj_hacmi', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ambalaj_birimi', models.CharField(choices=[('sise', 'Şişe'), ('kutu', 'Kutu'), ('torba', 'Torba'), ('teneke', 'Teneke'), ('diger', 'Diğer')], max_length=10)),
                ('ambalaj_birim', models.CharField(max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('onaylandi', models.BooleanField(default=False)),
                ('giris', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gübre',
                'verbose_name_plural': 'Gübreler',
                'ordering': ['ticari_ad'],
            },
        ),
        migrations.CreateModel(
            name='Ilac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticari_ad', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('fungisit', 'Fungisit'), ('insektisit', 'İnsektisit'), ('herbisit', 'Herbisit'), ('akarisit', 'Akarisit'), ('nematisit', 'Nematisit'), ('rodentisit', 'Rodentisit'), ('mollusisit', 'Mollüsisit'), ('diger', 'Diğer')], max_length=20)),
                ('formulasyon', models.CharField(max_length=50)),
                ('ruhsat_no', models.CharField(max_length=100)),
                ('phi_gun', models.PositiveIntegerField(verbose_name='PHI (Hasat Öncesi Bekleme Günü)')),
                ('bekleme_suresi', models.PositiveIntegerField(blank=True, null=True, verbose_name='İnsan Güvenliği Bekleme Süresi (gün)')),
                ('endikasyon', models.TextField(verbose_name='Endikasyon')),
                ('doz_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('doz_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('doz_birimi', models.CharField(max_length=50)),
                ('uygulama_yontemi', models.CharField(max_length=100)),
                ('kullanim_tavsiyesi', models.TextField(blank=True)),
                ('notlar', models.TextField(blank=True)),
                ('ambalaj_hacmi', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ambalaj_birimi', models.CharField(choices=[('sise', 'Şişe'), ('kutu', 'Kutu'), ('torba', 'Torba'), ('teneke', 'Teneke'), ('diger', 'Diğer')], max_length=10)),
                ('ambalaj_birim', models.CharField(max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('onaylandi', models.BooleanField(default=False)),
                ('giris', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İlaç',
                'verbose_name_plural': 'İlaçlar',
                'ordering': ['ticari_ad'],
            },
        ),
        migrations.CreateModel(
            name='Bayii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=200)),
                ('ruhsat_no', models.CharField(max_length=100)),
                ('il', models.CharField(max_length=100)),
                ('ilce', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bayii_profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bayii',
                'verbose_name_plural': 'Bayiiler',
                'ordering': ['firma_adi'],
            },
        ),
        migrations.CreateModel(
            name='BayiiUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True)),
                ('ekleme', models.DateTimeField(auto_now_add=True)),
                ('bayii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='katalog.bayii')),
                ('gubre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.gubre')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.ilac')),
            ],
            options={
                'verbose_name': 'Bayii Ürün',
                'verbose_name_plural': 'Bayii Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Uretici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=200)),
                ('vergi_no', models.CharField(max_length=20, unique=True)),
                ('adres', models.TextField()),
                ('yetkili', models.CharField(max_length=200)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uretici_profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üretici',
                'verbose_name_plural': 'Üreticiler',
                'ordering': ['firma_adi'],
            },
        ),
        migrations.AddField(
            model_name='ilac',
            name='uretici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilaclar', to='katalog.uretici'),
        ),
        migrations.AddField(
            model_name='gubre',
            name='uretici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gubreler', to='katalog.uretici'),
        ),
        migrations.CreateModel(
            name='GubreEtkenMadde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oran', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Oran (%)')),
                ('miktar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('miktar_birim', models.CharField(blank=True, max_length=20)),
                ('etken_madde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gubre_bilesenleri', to='katalog.etkenmadde')),
                ('gubre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etken_maddeler', to='katalog.gubre')),
            ],
            options={
                'verbose_name': 'Gübre Etken Madde',
                'verbose_name_plural': 'Gübre Etken Maddeler',
                'unique_together': {('gubre', 'etken_madde')},
            },
        ),
        migrations.CreateModel(
            name='IlacEtkenMadde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oran', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Oran (%)')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Miktar')),
                ('miktar_birim', models.CharField(max_length=20)),
                ('etken_madde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilac_bilesenleri', to='katalog.etkenmadde')),
                ('ilac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etken_maddeler', to='katalog.ilac')),
            ],
            options={
                'verbose_name': 'İlaç Etken Madde',
                'verbose_name_plural': 'İlaç Etken Maddeler',
                'unique_together': {('ilac', 'etken_madde')},
            },
        ),
        migrations.CreateModel(
            name='MuhendisBayii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.DateField()),
                ('aktif', models.BooleanField(default=True)),
                ('bayii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muhendisler', to='katalog.bayii')),
                ('muhendis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bayii_iliskisi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mühendis Bayii',
                'verbose_name_plural': 'Mühendis Bayiiler',
                'unique_together': {('muhendis', 'bayii')},
            },
        ),
    ]
