# Generated by Django 6.0.3 on 2026-04-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0008_adres_alanlari'),
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalFiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hal_sehir', models.CharField(max_length=100, verbose_name='Hal Şehri')),
                ('tarih', models.DateField(db_index=True, verbose_name='Hafta Tarihi')),
                ('fiyat_min', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Min Fiyat (₺/kg)')),
                ('fiyat_max', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Max Fiyat (₺/kg)')),
                ('fiyat_ort', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ort Fiyat (₺/kg)')),
                ('kaynak', models.CharField(blank=True, max_length=200, verbose_name='Kaynak')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hal_fiyatlar', to='ciftci.urun')),
            ],
            options={
                'verbose_name': 'Hal Fiyatı',
                'verbose_name_plural': 'Hal Fiyatları',
                'ordering': ['-tarih'],
                'indexes': [models.Index(fields=['urun', 'hal_sehir', 'tarih'], name='katalog_hal_urun_id_57d8c0_idx')],
                'unique_together': {('urun', 'hal_sehir', 'tarih')},
            },
        ),
    ]
