# Generated by Django 6.0.3 on 2026-04-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_halfiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayiiurun',
            name='stok',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stok (kg/lt/adet)'),
        ),
        migrations.AddField(
            model_name='bayiiurun',
            name='stok_esik',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Uyarı Eşiği'),
        ),
    ]
