# Generated by Django 6.0.3 on 2026-04-02 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Ciftci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_kodu', models.CharField(db_index=True, editable=False, max_length=8, unique=True)),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('cks_no', models.CharField(blank=True, max_length=100)),
                ('mahalle', models.CharField(blank=True, max_length=200)),
                ('ilce', models.CharField(max_length=100)),
                ('il', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('aktif', models.BooleanField(default=True)),
                ('kayit', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ciftci_profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Çiftçi',
                'verbose_name_plural': 'Çiftçiler',
                'ordering': ['-kayit'],
            },
        ),
        migrations.CreateModel(
            name='UrunCesit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cesitler', to='ciftci.urun')),
            ],
            options={
                'verbose_name': 'Ürün Çeşidi',
                'verbose_name_plural': 'Ürün Çeşitleri',
                'ordering': ['urun', 'ad'],
                'unique_together': {('urun', 'ad')},
            },
        ),
        migrations.CreateModel(
            name='Isletme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('tur', models.CharField(choices=[('sera', 'Sera'), ('acik_tarla', 'Açık Tarla'), ('meyve_bahce', 'Meyve Bahçesi'), ('zeytinlik', 'Zeytinlik'), ('diger', 'Diğer')], max_length=20)),
                ('sera_tip', models.CharField(blank=True, choices=[('naylon', 'Naylon'), ('cam', 'Cam'), ('policarbon', 'Polikarbon'), ('net', 'Net / Gölgelik'), ('diger', 'Diğer')], max_length=20, null=True)),
                ('alan_dekar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ekim_tarihi', models.DateField(blank=True, null=True)),
                ('enlem', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem (Latitude)')),
                ('boylam', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam (Longitude)')),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('ciftci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isletmeler', to='ciftci.ciftci')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_isletmeler', to=settings.AUTH_USER_MODEL)),
                ('urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciftci.urun')),
                ('cesit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciftci.uruncesit')),
            ],
            options={
                'verbose_name': 'İşletme',
                'verbose_name_plural': 'İşletmeler',
                'ordering': ['ciftci', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='MuhendisIsletme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('iptal', 'İptal')], default='bekliyor', max_length=20)),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yanit_tarihi', models.DateTimeField(blank=True, null=True)),
                ('isletme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muhendis_iliskileri', to='ciftci.isletme')),
                ('muhendis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isletme_iliskileri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mühendis İşletme',
                'verbose_name_plural': 'Mühendis İşletmeler',
                'unique_together': {('muhendis', 'isletme')},
            },
        ),
    ]
