# Generated by Django 6.0.3 on 2026-04-02 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0001_initial'),
        ('katalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CiftciBayii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='bekliyor', max_length=20)),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yanit_tarihi', models.DateTimeField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('baslatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baslattigi_iliskiler', to=settings.AUTH_USER_MODEL)),
                ('bayii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciftci_iliskileri', to='katalog.bayii')),
                ('ciftci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bayii_iliskileri', to='ciftci.ciftci')),
            ],
            options={
                'verbose_name': 'Çiftçi-Bayii İlişkisi',
                'unique_together': {('ciftci', 'bayii')},
            },
        ),
    ]
