# Generated by Django 6.0.3 on 2026-04-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0003_isletme_ciftci_isle_ciftci__295bfb_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToprakAnaliz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('organik_madde', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Organik Madde (%)')),
                ('fosfor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Fosfor (kg/da)')),
                ('potasyum', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Potasyum (kg/da)')),
                ('kalsiyum', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Kalsiyum (kg/da)')),
                ('magnezyum', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Magnezyum (kg/da)')),
                ('tuz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tuz (%)')),
                ('notlar', models.TextField(blank=True)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('isletme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toprak_analizler', to='ciftci.isletme')),
            ],
            options={
                'verbose_name': 'Toprak Analizi',
                'verbose_name_plural': 'Toprak Analizleri',
                'ordering': ['-tarih'],
            },
        ),
    ]
