# Generated by Django 6.0.3 on 2026-04-03 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0004_toprak_analiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsletmeFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='isletme_fotograflar/%Y/%m/')),
                ('aciklama', models.CharField(blank=True, max_length=200)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('isletme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='ciftci.isletme')),
                ('yukleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İşletme Fotoğrafı',
                'verbose_name_plural': 'İşletme Fotoğrafları',
                'ordering': ['-olusturma'],
            },
        ),
    ]
