# Generated by Django 6.0.3 on 2026-04-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0005_isletme_fotograf'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhendisisletme',
            name='baslatan',
            field=models.CharField(choices=[('muhendis', 'Mühendis'), ('ciftci', 'Çiftçi')], default='muhendis', max_length=20),
        ),
    ]
