# Generated by Django 6.0.3 on 2026-04-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0006_muhendisisletme_baslatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='isletme',
            name='ortualti_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Örtüaltı Tescil No'),
        ),
    ]
