# Generated by Django 6.0.3 on 2026-04-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0007_ortualti_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='isletme',
            name='ada_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ada No'),
        ),
        migrations.AddField(
            model_name='isletme',
            name='il',
            field=models.CharField(blank=True, max_length=100, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='isletme',
            name='ilce',
            field=models.CharField(blank=True, max_length=100, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='isletme',
            name='mahalle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mahalle / Köy'),
        ),
        migrations.AddField(
            model_name='isletme',
            name='parsel_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Parsel No'),
        ),
    ]
