# Generated by Django 6.0.3 on 2026-04-12 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0008_adres_alanlari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CiftciSorusu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField(verbose_name='Soru')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='ciftci_sorular/%Y/%m/')),
                ('ai_teshis', models.TextField(blank=True, verbose_name='AI Teşhis')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('yanitlandi', 'Yanıtlandı')], default='bekliyor', max_length=20)),
                ('yanit', models.TextField(blank=True, verbose_name='Mühendis Yanıtı')),
                ('yanit_tarihi', models.DateTimeField(blank=True, null=True)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('ciftci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='ciftci.ciftci')),
                ('isletme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorular', to='ciftci.isletme')),
                ('yanitleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yanitlenen_sorular', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Çiftçi Sorusu',
                'verbose_name_plural': 'Çiftçi Soruları',
                'ordering': ['-olusturma'],
            },
        ),
    ]
