# Generated by Django 6.0.3 on 2026-04-12 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0009_ciftci_sorusu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuhendisDuyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('metin', models.TextField()),
                ('il_filtre', models.CharField(blank=True, max_length=60, verbose_name='İl filtresi')),
                ('ilce_filtre', models.CharField(blank=True, max_length=60, verbose_name='İlçe filtresi')),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('muhendis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duyurular', to=settings.AUTH_USER_MODEL)),
                ('urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciftci.urun', verbose_name='Ürün filtresi')),
            ],
            options={
                'verbose_name': 'Mühendis Duyurusu',
                'verbose_name_plural': 'Mühendis Duyuruları',
                'ordering': ['-olusturma'],
            },
        ),
    ]
