# Generated by Django 6.0.3 on 2026-04-01 23:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('yonetici', 'Yönetici'), ('yardimci', 'Yardımcı'), ('muhendis', 'Mühendis'), ('ciftci', 'Çiftçi'), ('uretici', 'Üretici'), ('bayii', 'Bayii')], default='ciftci', max_length=20)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('il', models.CharField(blank=True, max_length=100)),
                ('ilce', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MuhendisIlce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=100)),
                ('ilce', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('muhendis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilceler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mühendis İlçe',
                'verbose_name_plural': 'Mühendis İlçeler',
                'unique_together': {('muhendis', 'il', 'ilce')},
            },
        ),
        migrations.CreateModel(
            name='YardimciYetki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetki', models.CharField(choices=[('muhendis_ekle', 'Mühendis Ekle'), ('muhendis_duzenle', 'Mühendis Düzenle'), ('muhendis_pasif', 'Mühendis Pasif Yap'), ('katalog_ekle', 'Katalog Ekle'), ('katalog_duzenle', 'Katalog Düzenle'), ('katalog_sil', 'Katalog Sil'), ('raporlar', 'Raporları Gör'), ('kullanici_yon', 'Kullanıcı Yönetimi')], max_length=50)),
                ('aktif', models.BooleanField(default=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('veren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verilen_yetkiler', to=settings.AUTH_USER_MODEL)),
                ('yardimci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkiler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yardımcı Yetki',
                'verbose_name_plural': 'Yardımcı Yetkiler',
                'unique_together': {('yardimci', 'yetki')},
            },
        ),
    ]
