# Generated by Django 6.0.3 on 2026-04-02 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciftci', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ziyaret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('saha', 'Saha Ziyareti'), ('danismanlik', 'Danışmanlık'), ('hasat', 'Hasat Kontrolü'), ('recete', 'Reçete Ziyareti'), ('numune', 'Numune Alma'), ('planlama', 'Sezon Planlaması')], max_length=20)),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('sure_dk', models.PositiveIntegerField(verbose_name='Süre (dakika)')),
                ('adres', models.TextField(blank=True)),
                ('notlar', models.TextField(blank=True)),
                ('tamamlandi', models.BooleanField(default=False)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('isletme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyaretler', to='ciftci.isletme')),
                ('muhendis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyaretler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ziyaret',
                'verbose_name_plural': 'Ziyaretler',
                'ordering': ['tarih', 'saat'],
            },
        ),
    ]
