# Generated by Django 6.0.3 on 2026-04-02 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciftci', '0001_initial'),
        ('katalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tani', models.CharField(max_length=300)),
                ('tarih', models.DateField()),
                ('uygulama_yontemi', models.CharField(max_length=100)),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('onaylandi', 'Onaylandı'), ('iptal', 'İptal')], default='taslak', max_length=20)),
                ('muhendis_notu', models.TextField(blank=True, verbose_name='Mühendis Notu (Sadece mühendis görür)')),
                ('hatirlatma', models.TextField(blank=True, verbose_name='Hatırlatma (Bildirim için)')),
                ('ciftciye_not', models.TextField(blank=True, verbose_name='Çiftçiye Not (Çiftçi görür)')),
                ('duzenleme_sayisi', models.PositiveIntegerField(default=0)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('isletme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receteler', to='ciftci.isletme')),
                ('muhendis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazilan_receteler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
                'ordering': ['-olusturma'],
            },
        ),
        migrations.CreateModel(
            name='ReceteFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='recete_fotograflar/%Y/%m/')),
                ('tip', models.CharField(choices=[('hastalik', 'Hastalık / Zararlı'), ('uygulama', 'Uygulama Sonrası'), ('genel', 'Genel')], default='genel', max_length=20)),
                ('aciklama', models.TextField(blank=True)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('recete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='recete.recete')),
                ('yukleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reçete Fotoğraf',
                'verbose_name_plural': 'Reçete Fotoğraflar',
                'ordering': ['olusturma'],
            },
        ),
        migrations.CreateModel(
            name='ReceteYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('soru', 'Soru'), ('yorum', 'Yorum'), ('yanit', 'Yanıt')], max_length=10)),
                ('metin', models.TextField()),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('recete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='recete.recete')),
                ('ust_yorum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yanitlar', to='recete.receteyorum')),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reçete Yorum',
                'verbose_name_plural': 'Reçete Yorumlar',
                'ordering': ['olusturma'],
            },
        ),
        migrations.CreateModel(
            name='UygulamaAdimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.PositiveIntegerField()),
                ('tip', models.CharField(choices=[('sulama', 'Sulama'), ('ilaclama', 'İlaçlama'), ('gubreleme', 'Gübreleme'), ('diger', 'Diğer')], max_length=20)),
                ('tanim', models.CharField(blank=True, max_length=200, verbose_name='Adım Adı')),
                ('uygulama_tarihi', models.DateField(blank=True, null=True)),
                ('tamamlandi', models.BooleanField(default=False)),
                ('notlar', models.TextField(blank=True)),
                ('recete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adimlar', to='recete.recete')),
            ],
            options={
                'verbose_name': 'Uygulama Adımı',
                'verbose_name_plural': 'Uygulama Adımları',
                'ordering': ['sira_no'],
                'unique_together': {('recete', 'sira_no')},
            },
        ),
        migrations.CreateModel(
            name='UygulamaAdimKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doz_dekar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dekara Doz')),
                ('birim', models.CharField(max_length=50)),
                ('adim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='recete.uygulamaadimi')),
                ('gubre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.gubre')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.ilac')),
            ],
            options={
                'verbose_name': 'Uygulama Adım Kalemi',
                'verbose_name_plural': 'Uygulama Adım Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='ReceteVersiyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiyon_no', models.PositiveIntegerField()),
                ('tani', models.CharField(max_length=300)),
                ('uygulama_yontemi', models.CharField(max_length=100)),
                ('notlar', models.TextField(blank=True)),
                ('kalemler', models.JSONField()),
                ('duzenleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('duzenleme_notu', models.TextField(blank=True)),
                ('duzenleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiyonlar', to='recete.recete')),
            ],
            options={
                'verbose_name': 'Reçete Versiyon',
                'verbose_name_plural': 'Reçete Versiyonlar',
                'ordering': ['-versiyon_no'],
                'unique_together': {('recete', 'versiyon_no')},
            },
        ),
    ]
