# Generated by Django 6.0.3 on 2026-04-03 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciftci', '0003_isletme_ciftci_isle_ciftci__295bfb_idx'),
        ('recete', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recete',
            name='ciftciye_not',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recete',
            name='hatirlatma',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recete',
            name='muhendis_notu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uygulamaadimi',
            name='tanim',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uygulamaadimkalemi',
            name='doz_dekar',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='recete',
            index=models.Index(fields=['muhendis', '-olusturma'], name='recete_rece_muhendi_d1f8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='recete',
            index=models.Index(fields=['isletme', '-tarih'], name='recete_rece_isletme_a05227_idx'),
        ),
        migrations.AddIndex(
            model_name='recete',
            index=models.Index(fields=['durum'], name='recete_rece_durum_b8065d_idx'),
        ),
    ]
