# Generated by Django 6.0.3 on 2026-04-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recete', '0002_alter_recete_ciftciye_not_alter_recete_hatirlatma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recete',
            name='tani',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
